### ISSUE TITLE
Installing Pelican on Python 3 and Windows yields UnicodeDecodeError

### ISSUE THREAD

**Issue by tchappui** [getpelican/pelican#1545]
Hi,

When installating pip on windows 7 with python 3.4, I get the following error (same error as https://github.com/getpelican/pelican/issues/1414):

```
Installing collected packages: pelican, python-dateutil, jinja2, docutils, blinker, feedgenerator, unidecode, pytz, six, pygments, markupsafe
Cleaning up...
Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\Python34\lib\site-packages\pip\req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "C:\Python34\lib\site-packages\pip\req.py", line 671, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "C:\Python34\lib\site-packages\pip\req.py", line 901, in move_wheel_files
    pycompile=self.pycompile,
  File "C:\Python34\lib\site-packages\pip\wheel.py", line 359, in move_wheel_files
    for row in reader:
  File "C:\Python34\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 7407: character maps to     <undefined>

Storing debug log for failure in C:\Users\admin\pip\pip.log
```

Issue 1414 was closed concluding to an encoding bug with pip. I don't think it is the case. Here are my observations:

I get this error when installing from pip, either locally or from PyPI. Installing from sources does not cause any problem. On windows, the problem already occurs when we build the wheel using setup.py and bdist_wheel. Hence, this is probably not a **pip specific problem**.

I search for all the files containing a 0x81 byte. All those files are located in the tests or themes directories. Consequently, I tried to rebuild the wheel file without the tests directory and the wheel archive builds and installs correctly. There is an encoding problem in one of the test files and I'm still searching for it.

This is a windows specific problem since somewhere during the construction/installation of the wheel, python tries to read a file and supposes it is encoded in cp 1252. However, the 0x81 byte does not mean anything in the 1252 windows encoring. I now have to search for the UTF-8 characters that contain a 0x81 byte in their representation.

Kind regards

Thierry

**Comment by vaibhavsagar** [comment]
I get a similar error even when I install with `pip install -U pelican --no-use-wheel` on Windows with Python 3.4:


        writing list of installed files to 'C:\Users\Vaibhav\AppData\Local\Temp\pip-qij1kl6n-record\install-record.txt'

        Traceback (most recent call last):

        File "<string>", line 1, in <module>

        File "C:\Users\Vaibhav\AppData\Local\Temp\pip-build-f1xo0x0r\pelican\setup.py", line 48, in <module>

            test_suite='pelican.tests',

        File "C:\Python34\lib\distutils\core.py", line 148, in setup

            dist.run_commands()

        File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands

            self.run_command(cmd)

        File "C:\Python34\lib\distutils\dist.py", line 974, in run_command

            cmd_obj.run()

        File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 61, in run

            return orig.install.run(self)

        File "C:\Python34\lib\distutils\command\install.py", line 566, in run

            self.record)

        File "C:\Python34\lib\distutils\cmd.py", line 336, in execute

            util.execute(func, args, msg, dry_run=self.dry_run)

        File "C:\Python34\lib\distutils\util.py", line 301, in execute

            func(*args)

        File "C:\Python34\lib\distutils\file_util.py", line 228, in write_file

            f.write(line + "\n")

        File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode

            return codecs.charmap_encode(input,self.errors,encoding_table)[0]

        UnicodeEncodeError: 'charmap' codec can't encode character '\u0301' in position 78: character maps to <undefined>

        ----------------------------------------
        Rolling back uninstall of pelican
        Command "C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Vaibhav\\Ap
    pData\\Local\\Temp\\pip-build-f1xo0x0r\\pelican\\setup.py';exec(compile(getattr(tokenize, 'open', op
    en)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Vaibhav\Ap
    pData\Local\Temp\pip-qij1kl6n-record\install-record.txt --single-version-externally-managed --compil
    e" failed with error code 1 in C:\Users\Vaibhav\AppData\Local\Temp\pip-build-f1xo0x0r\pelican

**Comment by robertlagrant** [comment]
Just FYI I get something similar on Windows 7:

````
Installing collected packages: pelican, feedgenerator, unidecode, blinker, pygments, docutils, jinja2, six, python-dateutil, pytz, markupsafe
Cleaning up...
  Removing temporary dir C:\github\repo\venv\build...
Exception:
Traceback (most recent call last):
  File "C:\github\repo\venv\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\github\repo\venv\lib\site-packages\pip\commands\install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\github\repo\venv\lib\site-packages\pip\req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "C:\github\repo\venv\lib\site-packages\pip\req.py", line 671, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "C:\github\repo\venv\lib\site-packages\pip\req.py", line 901, in move_wheel_files
    pycompile=self.pycompile,
  File "C:\github\repo\venv\lib\site-packages\pip\wheel.py", line 359, in move_wheel_files
    for row in reader:
  File "C:\github\repo\venv\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 7822: character maps to <undefined>

````

**Comment by robertlagrant** [comment]
Weirdly, it still works. It just doesn't seem to set up whatever pip needs to be aware that it's installed, as uninstalling doesn't work. But other than that it seems fine.

**Comment by justinmayer** [comment]
This should be addressed in 3.6, [which was just released](http://blog.getpelican.com/pelican-3.6-released.html).

**Comment by vaibhavsagar** [comment]
No luck for me, `pip install --upgrade pelican --no-use-wheel` fails at the very end:

```
    writing list of installed files to 'C:\Users\Vaibhav\AppData\Local\Temp\pip-al84udr3-record\install-record.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Vaibhav\AppData\Local\Temp\pip-build-pi96qumd\pelican\setup.py", line 48, in <module>
        test_suite='pelican.tests',
      File "C:\Python34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Python34\lib\distutils\command\install.py", line 566, in run
        self.record)
      File "C:\Python34\lib\distutils\cmd.py", line 336, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "C:\Python34\lib\distutils\util.py", line 301, in execute
        func(*args)
      File "C:\Python34\lib\distutils\file_util.py", line 228, in write_file
        f.write(line + "\n")
      File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u0301' in position 78: character maps to <undefined>

    ----------------------------------------
  Rolling back uninstall of pelican
Command "C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Vaibhav\\AppDat
a\\Local\\Temp\\pip-build-pi96qumd\\pelican\\setup.py';exec(compile(getattr(tokenize, 'open', open)(
__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\Vaibhav\AppDat
a\Local\Temp\pip-al84udr3-record\install-record.txt --single-version-externally-managed --compile" f
ailed with error code 1 in C:\Users\Vaibhav\AppData\Local\Temp\pip-build-pi96qumd\pelican
```

**Comment by tchappui** [comment]
I still get the same problem with Pytrhon 3.4.3 and Pelican 3.6

    (essai) D:\Dropbox\dev>pip install pelican
    Collecting pelican
      Downloading pelican-3.6.0-py2.py3-none-any.whl (525kB)
        100% |################################| 528kB 437kB/s
    Collecting six>=1.4 (from pelican)
      Using cached six-1.9.0-py2.py3-none-any.whl
    Collecting jinja2>=2.7 (from pelican)
    Collecting pygments (from pelican)
      Using cached Pygments-2.0.2-py3-none-any.whl
    Collecting python-dateutil (from pelican)
      Using cached python_dateutil-2.4.2-py2.py3-none-any.whl
    Collecting unidecode (from pelican)
      Downloading Unidecode-0.04.18.tar.gz (206kB)
        100% |################################| 208kB 524kB/s
    Collecting pytz>=0a (from pelican)
      Using cached pytz-2015.4-py2.py3-none-any.whl
    Collecting docutils (from pelican)
      Using cached docutils-0.12-py3-none-any.whl
    Collecting feedgenerator>=1.6 (from pelican)
    Collecting blinker (from pelican)
    Collecting markupsafe (from jinja2>=2.7->pelican)
    Building wheels for collected packages: unidecode
      Running setup.py bdist_wheel for unidecode
      Stored in directory: C:\Users\thierry.chappuis\AppData\Local\pip\Cache\wheels\
a8\85\b6\71cbccded974d5a8e15cbe7d22066d87f34329d98c7ed5d786
    Successfully built unidecode
    Installing collected packages: six, markupsafe, jinja2, pygments, python-dateuti
l, unidecode, pytz, docutils, feedgenerator, blinker, pelican
    Exception:
    Traceback (most recent call last):
      File "C:\Users\thierry.chappuis\Envs\essai\lib\site-packages\pip\basecommand.p
y", line 223, in main
        status = self.run(options, args)
  File "C:\Users\thierry.chappuis\Envs\essai\lib\site-packages\pip\commands\inst
all.py", line 297, in run
    root=options.root_path,
      File "C:\Users\thierry.chappuis\Envs\essai\lib\site-packages\pip\req\req_set.p
y", line 622, in install
    **kwargs
      File "C:\Users\thierry.chappuis\Envs\essai\lib\site-packages\pip\req\req_insta
ll.py", line 808, in install
    self.move_wheel_files(self.source_dir, root=root)
      File "C:\Users\thierry.chappuis\Envs\essai\lib\site-packages\pip\req\req_insta
ll.py", line 1003, in move_wheel_files
    isolated=self.isolated,
      File "C:\Users\thierry.chappuis\Envs\essai\lib\site-packages\pip\wheel.py", li
ne 495, in move_wheel_files
        for row in reader:
     File "C:\Users\thierry.chappuis\Envs\essai\lib\encodings\cp1252.py", line 23,
    in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 123: char
acter maps to <undefined>

**Comment by justinmayer** [comment]
Presumably this will be addressed by ensuring tests are not included in bdist (see #1618).

**Comment by MinchinWeb** [comment]
#1609 and #1409 seem to be duplicates.

**Comment by tchappui** [comment]
Yes, #1609 is a duplicate. Probably, #1409 is a duplicate but reports the same problem on linux depending on the locale. Both #1545 and #1609 concern Windows.

Kind regards

Thierry

**Comment by abdurrafi13** [comment]
# I'm too having the same problem!!


===============================================================================
Windows PowerShell
Copyright (C) 2012 Microsoft Corporation. All rights reserved.

PS C:\Users\user> pip install markdown
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Collecting markdown
  Downloading Markdown-2.6.2-py2.py3-none-any.whl (157kB)
    100% |################################| 159kB 49kB/s
Installing collected packages: markdown
Successfully installed markdown-2.6.2
PS C:\Users\user> pip install pelican
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Collecting pelican
  Downloading pelican-3.6.0-py2.py3-none-any.whl (525kB)
    100% |################################| 528kB 44kB/s
Collecting python-dateutil (from pelican)
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pygments in c:\python34\lib\site-packages (from pelican)
Requirement already satisfied (use --upgrade to upgrade): unidecode in c:\python34\lib\site-packages (from pelican)
Requirement already satisfied (use --upgrade to upgrade): blinker in c:\python34\lib\site-packages (from pelican)
Collecting feedgenerator>=1.6 (from pelican)
  Downloading feedgenerator-1.7.tar.gz
Requirement already satisfied (use --upgrade to upgrade): docutils in c:\python34\lib\site-packages (from pelican)
Requirement already satisfied (use --upgrade to upgrade): jinja2>=2.7 in c:\python34\lib\site-packages (from pelican)
Requirement already satisfied (use --upgrade to upgrade): pytz>=0a in c:\python34\lib\site-packages (from pelican)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4 in c:\python34\lib\site-packages (from pelican)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in c:\python34\lib\site-packages (from jinja2>=2.7-
>pelican)
Installing collected packages: python-dateutil, feedgenerator, pelican
  Running setup.py install for feedgenerator
Exception:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 223, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 297, in run
    root=options.root_path,
  File "C:\Python34\lib\site-packages\pip\req\req_set.py", line 622, in install
    **kwargs
  File "C:\Python34\lib\site-packages\pip\req\req_install.py", line 808, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "C:\Python34\lib\site-packages\pip\req\req_install.py", line 1003, in move_wheel_files
    isolated=self.isolated,
  File "C:\Python34\lib\site-packages\pip\wheel.py", line 495, in move_wheel_files
    for row in reader:
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 123: character maps to <undefined>
===============================================================================

**Comment by justinmayer** [comment]
Presumably addressed via #1778, which will be included in the next release.

**Comment by AldenMB** [comment]
I am still getting this error on Windows with Pelican 4.8.0, installing with Conda. For example, `pelican/tests/output/custom_locale/posts/2010` has a folder named `d├⌐cembre`, and folders in `2011` and `2012` are named `f├⌐vrier`. Correcting the folder names allows the install to complete. For what it's worth, I am installing from `conda-forge` by asking for `pelican[markdown]`. Below is the error which initially prevents the install.

```
Verifying transaction: ...working... failed
Traceback (most recent call last):
  File "C:\Users\alden\anaconda3\lib\site-packages\conda\exceptions.py", line 1129, in __call__
    return func(*args, **kwargs)
  File "C:\Users\alden\anaconda3\lib\site-packages\conda_env\cli\main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Users\alden\anaconda3\lib\site-packages\conda\notices\core.py", line 72, in wrapper
    return_value = func(*args, **kwargs)
  File "C:\Users\alden\anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 156, in execute
    result[installer_type] = installer.install(prefix, pkg_specs, args, env)
  File "C:\Users\alden\anaconda3\lib\site-packages\conda_env\installers\conda.py", line 59, in install
    unlink_link_transaction.execute()
  File "C:\Users\alden\anaconda3\lib\site-packages\conda\core\link.py", line 280, in execute
    self.verify()
  File "C:\Users\alden\anaconda3\lib\site-packages\conda\common\io.py", line 86, in decorated
    return f(*args, **kwds)
  File "C:\Users\alden\anaconda3\lib\site-packages\conda\core\link.py", line 244, in verify
    maybe_raise(CondaMultiError(exceptions), context)
  File "C:\Users\alden\anaconda3\lib\site-packages\conda\exceptions.py", line 1069, in maybe_raise
    raise error
conda.CondaMultiError: The package for pelican located at C:\Users\alden\anaconda3\pkgs\pelican-4.8.0-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/pelican/tests/output/custom_locale/posts/2010/décembre/02/this-is-a-su'
specified in the package manifest cannot be found.

The package for pelican located at C:\Users\alden\anaconda3\pkgs\pelican-4.8.0-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/pelican/tests/output/custom_locale/posts/2011/février/17/article-1/ind'
specified in the package manifest cannot be found.

The package for pelican located at C:\Users\alden\anaconda3\pkgs\pelican-4.8.0-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/pelican/tests/output/custom_locale/posts/2011/février/17/article-2/ind'
specified in the package manifest cannot be found.

The package for pelican located at C:\Users\alden\anaconda3\pkgs\pelican-4.8.0-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/pelican/tests/output/custom_locale/posts/2011/février/17/article-3/ind'
specified in the package manifest cannot be found.

The package for pelican located at C:\Users\alden\anaconda3\pkgs\pelican-4.8.0-pyhd8ed1ab_0
appears to be corrupted. The path 'site-packages/pelican/tests/output/custom_locale/posts/2012/février/29/second-articl'
specified in the package manifest cannot be found.
```

**Comment by s-bear** [comment]
@AldenMB I just ran into this problem myself. I dug into it a bit and found that the filenames are encoded correctly in pelican's package files on conda-forge, but conda was mangling them on extraction. Upgrading conda (to 22.11)  and conda-package-handling (to v 2.02) fixed the issue.
Cheers, Sam
