### ISSUE TITLE
Can't install in Windows 8.1 with WindowsError [Error 123]

### ISSUE THREAD

**Issue by joshua-huh** [getpelican/pelican#1569]
Tried to install pelican in Windows 8.1 but failed to install with an error, WindowsError: [Error 123], which seems related to file name. Below is the output of my powershell.

```
(blog)PS C:\Users\x\Documents\GitHub\blog> workon

PathInfo                      Name                          PathToScripts                 PathToSitePackages
--------                      ----                          -------------                 ------------------
blog                          blog                          C:\Users\x\.virtualen... C:\Users\x\.virtualen...


(blog)PS C:\Users\x\Documents\GitHub\blog> pip install -r .\requirements.txt
Collecting Jinja2==2.7.3 (from -r .\requirements.txt (line 1))
  Using cached Jinja2-2.7.3.tar.gz
Requirement already satisfied (use --upgrade to upgrade): Markdown==2.5.2 in c:\users\joshua\.virtualenvs\blog\lib\site-packages (from -r .\requirements.txt (line 2))
Collecting MarkupSafe==0.23 (from -r .\requirements.txt (line 3))
  Using cached MarkupSafe-0.23.tar.gz
Collecting Pygments==2.0.1 (from -r .\requirements.txt (line 4))
  Using cached Pygments-2.0.1-py2-none-any.whl
Collecting Unidecode==0.04.17 (from -r .\requirements.txt (line 5))
  Using cached Unidecode-0.04.17.tar.gz
    C:\Users\x\.virtualenvs\blog\lib\site-packages\setuptools\dist.py:289: UserWarning: The version specified requires normalization, consider using '0.4.17' instead of '0.04.17'.
      self.metadata.version,
Collecting argparse==1.2.1 (from -r .\requirements.txt (line 6))
  Using cached argparse-1.2.1.tar.gz
Collecting blinker==1.3 (from -r .\requirements.txt (line 7))
  Using cached blinker-1.3.tar.gz
Collecting docutils==0.12 (from -r .\requirements.txt (line 8))
  Using cached docutils-0.12.tar.gz
Collecting feedgenerator==1.7 (from -r .\requirements.txt (line 9))
  Using cached feedgenerator-1.7.tar.gz
Collecting pelican==3.5.0 (from -r .\requirements.txt (line 10))
  Using cached pelican-3.5.0-py2.py3-none-any.whl
  Exception:
  Traceback (most recent call last):
    File "C:\Users\x\.virtualenvs\blog\lib\site-packages\pip\basecommand.py", line 215, in main
      status = self.run(options, args)
    File "C:\Users\x\.virtualenvs\blog\lib\site-packages\pip\commands\install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "C:\Users\x\.virtualenvs\blog\lib\site-packages\pip\req\req_set.py", line 355, in prepare_files
      do_download, session=self.session,
    File "C:\Users\x\.virtualenvs\blog\lib\site-packages\pip\download.py", line 748, in unpack_url
      session,
    File "C:\Users\x\.virtualenvs\blog\lib\site-packages\pip\download.py", line 637, in unpack_http_url
      unpack_file(from_path, location, content_type, link)
    File "C:\Users\x\.virtualenvs\blog\lib\site-packages\pip\utils\__init__.py", line 645, in unpack_file
      flatten=not filename.endswith('.whl')
    File "C:\Users\x\.virtualenvs\blog\lib\site-packages\pip\utils\__init__.py", line 535, in unzip_file
      os.makedirs(dir)
    File "C:\Users\x\.virtualenvs\blog\lib\os.py", line 150, in makedirs
      makedirs(head, mode)
    File "C:\Users\x\.virtualenvs\blog\lib\os.py", line 150, in makedirs
      makedirs(head, mode)
    File "C:\Users\x\.virtualenvs\blog\lib\os.py", line 157, in makedirs
      mkdir(name, mode)
  WindowsError: [Error 123] 파일 이름,: 'c:\\users\\x\\appdata\\local\\temp\\pip-build-balfb0\\pelican\\pelican/tests/output/custom_locale/posts/2010/de\xcc\x81cembre'
```

My system baseline is below
* Operating System: Windows 8.1 (64bit)
* Python: 2.7.9
* Enviroment variables
`PATH=C:\Python27\;C:\Python27\Scripts;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\`

**Comment by justinmayer** [comment]
This was possibly addressed in 3.6, [which was just released](http://blog.getpelican.com/pelican-3.6-released.html). Would you please test and let us know?

**Comment by joshua-huh** [comment]
Not resolved. Some part of message encoded too poorly to read. The output is below:

C:\Users\x>pip install pelican
Collecting pelican
  Using cached pelican-3.6.0-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 223, in main
    status = self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 282, in run

    requirement_set.prepare_files(finder)
  File "C:\Python27\lib\site-packages\pip\req\req_set.py", line 334, in prepare_
files
    functools.partial(self._prepare_file, finder))
  File "C:\Python27\lib\site-packages\pip\req\req_set.py", line 321, in _walk_re
q_to_install
    more_reqs = handler(req_to_install)
  File "C:\Python27\lib\site-packages\pip\req\req_set.py", line 491, in _prepare
_file
    session=self.session)
  File "C:\Python27\lib\site-packages\pip\download.py", line 825, in unpack_url
    session,
  File "C:\Python27\lib\site-packages\pip\download.py", line 677, in unpack_http
_url
    unpack_file(from_path, location, content_type, link)
  File "C:\Python27\lib\site-packages\pip\utils\__init__.py", line 644, in unpac
k_file
    flatten=not filename.endswith('.whl')
  File "C:\Python27\lib\site-packages\pip\utils\__init__.py", line 544, in unzip
_file
    ensure_dir(dir)
  File "C:\Python27\lib\site-packages\pip\utils\__init__.py", line 70, in ensure
_dir
    os.makedirs(path)
  File "C:\Python27\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Python27\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 123] ÆÄÀÏ ÀÌ¸§,: 'c:\\users\\x\\appdata\\local\\temp\\
pip-build-kwkm3s\\pelican\\pelican/tests/output/custom_locale/posts/2010/de\xcc\
x81cembre'

**Comment by justinmayer** [comment]
Most likely resolved in current master, which will show up in the next release.

**Comment by justinmayer** [comment]
@joshua-huh: If this issue still persists, please comment here and I will re-open the issue.
