### ISSUE TITLE
SyntaxWarning in pelican_themes.py

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2810]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Linux arca 5.8.0-2-amd64 #1 SMP Debian 5.8.10-1 (2020-09-19)
- **Python version**: Python 3.8.6
- **Pelican version**: 4.0.1+dfsg-1_all
- **Link to theme**: n/a
- **Links to plugins**: n/a
- **Link to your site**: n/a
- **Link to your source**: n/a
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: n/a

## Issue
Due to plugin issue in Pelican 4.5.0, I had to revert back to Debian Bullseye (11) variant of Pelican (4.0.1-xxxxx), but got some kind of warnings.
```console
# apt  install pelican
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  pandoc pelican-doc
The following NEW packages will be installed:
  pelican
0 upgraded, 1 newly installed, 0 to remove and 44 not upgraded.
Need to get 94.4 kB of archives.
After this operation, 412 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian testing/main amd64 pelican all 4.0.1+dfsg-1 [94.4 kB]
Fetched 94.4 kB in 0s (525 kB/s)
Selecting previously unselected package pelican.
(Reading database ... 338973 files and directories currently installed.)
Preparing to unpack .../pelican_4.0.1+dfsg-1_all.deb ...
Unpacking pelican (4.0.1+dfsg-1) ...
Setting up pelican (4.0.1+dfsg-1) ...
/usr/lib/python3/dist-packages/pelican/tools/pelican_themes.py:84: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if args.action is 'list':
/usr/lib/python3/dist-packages/pelican/tools/pelican_themes.py:86: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif args.action is 'path':
Processing triggers for man-db (2.9.3-2) ...
Scanning processes...                                                           
Scanning candidates...                                                          
Scanning processor microcode...                                                 
Scanning linux images...                                                        
Running kernel seems to be up-to-date.
Failed to check for processor microcode upgrades.
Restarting services...
#
```
I searched this issue database for `SyntaxWarning` and got no hit.  So, just thought  that it might still be an issue, just in case.

If this is no longer an issue, just close it,  please.

**Comment by egberts** [comment]
I just checked latest (4.5.0/master) of [pelican_themes.py:82](https://github.com/getpelican/pelican/blob/7a6686f4679adabdd690668a4ba7cedaf494e243/pelican/tools/pelican_themes.py#L82) ...

And this issue has been fixed.

**Comment by johnfraney** [comment]
@egberts Glad I could help!

**Comment by stolk** [comment]
Sadly, anybody installing this on the **current** Ubuntu LTS still gets this error! Ubuntu LTS is on 4.0.1+dfsg-1.
